matrix:
  include:
    - language: r
      r:
        - "3.5.1"
        - oldrel
        - release
      install:
        - Rscript -e 'install.packages(c("stringr","magrittr","ggplot2","reshape2"))'
    
    - language: python
      python:
        - "3.6"
        - "3.7.3"
        - "3.8"
      install:
        - sudo apt-get update
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        # Useful for debugging any issues with conda
        - conda info -a
        # Replace dep1 dep2 ... with your dependencies
        - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
        - conda activate test-environment
        - while read requirement; do conda install $requirement; done < requirements.txt
      script:
        - cd tests
        - coverage run --source=NeuralSimODE -m unittest discover -s .
      after_success:
        - coveralls
